# Location where the relay will store its data
database_dir: "./data"

# Listen address of dtan relay
listen: "0.0.0.0:8000"

# Bootstrap relays to discover content
relays:
  - "wss://relay.damus.io"
  - "wss://nos.lol"
  - "wss://relay.nostr.band"
  - "wss://relay.snort.social"

# Explicitly set your public IP for DHT (default NAT-PMP / Main public IP)
dht_public_ip: "140.140.140.140"

# Path to DTAN web site build (default www dir)
web_dir: "../dtan/dist"

# Use DHT to discover other DTAN server peers
# use_dht: false

# Only accept 1 torrent per info_hash
# distinct_info_hash: false